### ISSUE TITLE
[Meta] Should we move related repos into the organisation?

### ISSUE THREAD

**Issue by fwcd** [pesca-dev/moneyboy-app#43]
Currently, [`moneyboy-app`](https://github.com/H1ghBre4k3r/moneyboy-app) and [`moneyboy-backend-go`](https://github.com/H1ghBre4k3r/moneyboy-backend-go) are hosted under `H1ghBre4k3r` while [`moneyboy-artwork`](https://github.com/pesca-dev/moneyboy-artwork) is under `pesca-dev`. For clarity, I would propose that we either

- Move all `moneyboy-...` repos into `pesca-dev`
    => Would have the advantage of making it easier for other contributors to create new related repos
- Move `moneyboy-artwork` into `H1ghBre4k3r`

Note that if we go with the first case, we may have to update some URLs e.g. from the badges in the README.

**Comment by H1ghBre4k3r** [comment]
Done @fwcd
